import '@fortawesome/fontawesome-free/css/all.css'
import './application.scss'
import './login/style.scss'
import './search/style.scss'
import './pagination.scss'
import './page/style.scss'
import './actiontext.scss'